[
  {
    "first_name": "James",
    "zip": 70.116
  },
  {
    "first_name": "Josephine",
    "zip": 48.816
  },
  {
    "first_name": "Art",
    "zip": 80.142
  },
  {
    "first_name": "Lenna",
    "zip": 9.9501
  }
]