#%RAML 1.0
title: errorHandling
version: v1
baseUri: http://localhost:8081/api

traits:
  client : !include /trait/trait.raml
    

/validation:
  description: validating the email and customize the error response 
  get:
    is:
      - client
    responses:
      200:
        body:
          application/json:
            example:
              {
                  "emailReceived" : "rick@gmail.com",
                  "name" : "rick"
              }
/dataWeave:
  description: validating the email and customize the error response 
  get:
    is:
      - client
    responses:
      200:
        body:
          application/json:
            example: !include /examples/dataWeaveRequest.raml
